title: HyperRealitIE 2014
description: Workshop on Hyperrealistic Intelligent Environments
baseurl: ""  # Leave empty for root domain
url: "https://hyperrealitie.org"

theme: minima

minima:
  include:
    - head-custom.html
    
plugins:
  - jekyll-seo-tag