title: HyperRealitIE 2014
description: Workshop on Hyperrealistic Intelligent Environments
url: "https://hyperrealitie.org"
baseurl: ""  # root of domain

theme: null
remote_theme: daviddarnes/alembic

plugins:
  - jekyll-remote-theme