title: HyperRealitIE 2014
description: Workshop on Hyperrealistic Intelligent Environments
baseurl: "" # Leave this empty since your site is at the root domain
url: "https://hyperrealitie.org" # Your site's URL

theme: null
remote_theme: daviddarnes/alembic

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag