title: HyperRealitIE 2014
url: "https://hyperrealitie.org"
baseurl: ""  # ← MUST be blank when using a custom domain
description: Static site for the Workshop on Hyperrealistic Intelligent Environments 2014
theme: minima # Optional: Jekyll’s default theme