title: HyperRealitIE 2014
description: Workshop on Hyperrealistic Intelligent Environments
url: "http://127.0.0.1:4000"
baseurl: ""  # root of domain

theme: null
remote_theme: daviddarnes/alembic

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag